name: VST.NET2 CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - uses: nuget/setup-nuget@v1
        with:
          nuget-version: latest
      - name: Restore Dependencies
        run: dotnet restore Source/Code/Jacobi.Vst.sln
      - name: Build VST.NET
        run: dotnet build Source/Code/Jacobi.Vst.sln --configuration Release /p:Platform=x64
      - name: Build VST.NET x86
        run: dotnet build Source/Code/Jacobi.Vst.sln --configuration Release /p:Platform=x86
